name: learnwithme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.5.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^0.13.6
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/numbers/
    - assets/Stories/
    - assets/Alphabets/
    - assets/fonts/
    - assets/Animals/
    - assets/icons/
    - assets/json/letters.json
    - assets/json/animals.json
    - assets/json/numbers.json
    - assets/json/stories.json

  fonts:
    - family: MVBoli
      fonts:
        - asset: assets/fonts/mv-boli.ttf
