name: learnwithme
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.5.0
  chewie: ^1.11.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  http: ^0.13.6
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/numbers/
    - assets/Stories/
    - assets/Alphabets/
    - assets/fonts/
    - assets/Animals/
    - assets/icons/
    - assets/json/all_letters.json
    - assets/json/letters_details.json
    - assets/json/animals.json
    - assets/json/numbers.json
    - assets/json/stories.json

  fonts:
    - family: MVBoli
      fonts:
        - asset: assets/fonts/mv-boli.ttf
